### ISSUE TITLE
Bad state : No element & not in inlcusive range

### ISSUE THREAD

**Issue by VirtualAstronaut** [tolo/id3tag#1]
`[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Bad state: No element`

parsing Careless whispermp3 gives that warning i checked it has album art/picture but its not detecting.

`Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 264..171467: 619626`

parsing never count on me.mp3 gives this error

[LINK to songs](https://drive.google.com/drive/folders/1omSqtlFqOELTJ1_PFXlz9K8kM_tNex76?usp=sharing)
code snippet:

```
  final parser =  ID3TagReader.path(songsList[index].path);
  final tags = parser.readTagSync(); 
  albumArt = Uint8List.fromList(tags.pictures.first.imageData);
```

**Comment by tolo** [comment]
Sorry for the exceptionally late reply. I've located the problem and a fix will be available shortly.

**Comment by VirtualAstronaut** [comment]
yeah, no worries :D
